data:
  image: busybox
  volumes:
    - .:/usr/src/myapp

python3-server:
  image: "cvgenerator/generator"
  command: ["python3", "-u", ".", "server"]
  volumes_from:
    - data
  working_dir: /usr/src/myapp

python3-worker:
  image: "cvgenerator/generator"
  command: ["python3", "-u", ".", "queue", "10.10.33.204", "8444"]
  volumes_from:
    - data
  working_dir: /usr/src/myapp
